global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "authors-app"
    scrape_interval: 10s
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['authors:8080']

  - job_name: "books-app"
    scrape_interval: 10s
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['books:8080']

  - job_name: "customers-app"
    scrape_interval: 10s
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['customers:8080']

  - job_name: 'traefik'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['proxy:8082']